name: build
# Events configuration
on:
  # Execute it on pushing to next branches
  push:
    branches:
      - main
  # Execute it on opening any pull request
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Install Pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: '7.x'
      # Install Node.js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'pnpm'
      # Install workspace dependencies
      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm lint:all

      - name: Run builds
        run: pnpm build:all

      - name: Run tests
        run: pnpm test:all

  build-finished:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    if: always() && needs.build-and-test.result == 'success'
    steps:
      - name: Trace
        run: echo "Test and build finished successfully"
