name: publish
# Events configuration
on:
  workflow_dispatch:
    inputs:
      publish_js_sdk:
        description: Publish JS SDK
        required: true
        type: boolean
        default: false
      publish_react_sdk:
        description: Publish React SDK
        required: true
        type: boolean
        default: false
      publish_vue_sdk:
        description: Publish Vue SDK
        required: true
        type: boolean
        default: false
      version_major:
        description: Bump major version
        required: true
        type: boolean
        default: false
      version_minor:
        description: Bump minor version
        required: true
        type: boolean
        default: false
      version_patch:
        description: Bump patch version
        required: true
        type: boolean
        default: true

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: '7.x'
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'
      - name: PNPM install
        run: pnpm install

      # Bump JS SDK
      - name: Bump package major version for JS SDK
        run: pnpm version major
        if: ${{ inputs.publish_js_sdk && inputs.version_major }}
        working-directory: ./packages/core-js
      - name: Bump package monor version for JS SDK
        run: pnpm version minor
        if: ${{ inputs.publish_js_sdk && inputs.version_minor }}
        working-directory: ./packages/core-js
      - name: Bump package patch version for JS SDK
        run: pnpm version patch
        if: ${{ inputs.publish_js_sdk && inputs.version_patch }}
        working-directory: ./packages/core-js

      # Bump React SDK
      - name: Bump package major version for React SDK
        run: pnpm version major
        if: ${{ inputs.publish_react_sdk && inputs.version_major }}
        working-directory: ./packages/react
      - name: Bump package minor version for React SDK
        run: pnpm version minor
        if: ${{ inputs.publish_react_sdk && inputs.version_minor }}
        working-directory: ./packages/react
      - name: Bump package patch version for React SDK
        run: pnpm version patch
        if: ${{ inputs.publish_react_sdk && inputs.version_patch }}
        working-directory: ./packages/react

      # Bump Vue SDK
      - name: Bump package major version for Vue SDK
        run: pnpm version major
        if: ${{ inputs.publish_vue_sdk && inputs.version_major }}
        working-directory: ./packages/vue
      - name: Bump package minor version for Vue SDK
        run: pnpm version minor
        if: ${{ inputs.publish_vue_sdk && inputs.version_minor }}
        working-directory: ./packages/vue
      - name: Bump package patch version for Vue SDK
        run: pnpm version patch
        if: ${{ inputs.publish_vue_sdk && inputs.version_patch }}
        working-directory: ./packages/vue

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated version bump
          commit_options: '--no-verify'

      - name: Build applications
        run: pnpm run build:all

      # Publish JS SDK
      - run: pnpm publish --no-git-checks
        if: ${{ inputs.publish_js_sdk }}
        working-directory: ./packages/core-js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      # Publish React SDK
      - run: pnpm publish --no-git-checks
        if: ${{ inputs.publish_react_sdk }}
        working-directory: ./packages/react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      # Publish Vue SDK
      - run: pnpm publish --no-git-checks
        if: ${{ inputs.publish_vue_sdk }}
        working-directory: ./packages/vue
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
